staging:
  deploy_to: "/var/www/consul"
  ssh_port: 21
  server: <%= ENV['MAIN_URL'] %>
  db_server: <%= ENV['POSTGRES_DATABASE'] %>
  user: "consul"
  server_name: <%= ENV['MAIN_URL'] %>
  full_app_name: "consul"

preproduction:
  deploy_to: "/var/www/consul"
  ssh_port: 2222
  server1: <%= ENV['SERVER_IP'] %>
  server2: xxx.xxx.xxx.xxx
  db_server: <%= ENV['POSTGRES_DATABASE'] %>
  user: xxxxx
  server_name: pre.consul.es
  full_app_name: "consul"

production:
  deploy_to: "/var/www/consul"
  ssh_port: 22
  server: <%= ENV['SERVER_IP'] %>
  db_server: <%= ENV['POSTGRES_DATABASE'] %>
  user: "consul"
  server_name: <%= ENV['MAIN_URL'] %>
  full_app_name: "consul"
